default_stages: [commit, push, manual]
repos:
  - repo: local
    hooks:
      - id: dco-sign-off
        name: DCO Sign-off
        entry: sh bin/add-dco-signoff.sh
        stages: [prepare-commit-msg]
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, golden]
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  - repo: local  # Prefer local tools to streamline version management with poetry
    hooks:
      # Rewriters
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade --keep-runtime-typing --py39-plus
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: blacken-docs
        name: blacken-docs
        entry: blacken-docs
        language: system
        types_or: [markdown, python]
      # Checkers
      - id: bandit
        name: bandit
        entry: bandit -ll -r
        files: '^src/'
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: bash -c
        args:
          - >
            if [[ $(git branch --show-current) == "golden" ]]; then
              pytest
            else
              # If tests become too slow, mark slow ones and omit. We'll add a little coverage buffer for working
              # commits, though CI/PRs will still enforce 100%.
              pytest --cov-fail-under=90
            fi
        language: system
        pass_filenames: false
        types: [python]
